services:
  front-maisvalorlabs:
    container_name: front-maisvalorlabs-dev
    build:
      context: .
      target: development
    ports:
      - 5173:5173
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: npm run dev -- --host
